# This file was generated by GoReleaser. DO NOT EDIT.
cask "localotelviewer" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "2fdbd358dbfcd886ddaf0e35528921365e1815ca0eec1910434242f9f47842db"
      url "https://github.com/shibukawa/localotelviewer/releases/download/v#{version}/localotelviewer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "26c1131a83b04ffa4fc41350e2b3fbe27f5888245cce5143e2f1ca92937d5879"
      url "https://github.com/shibukawa/localotelviewer/releases/download/v#{version}/localotelviewer_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a86eef40cbf1edee620beafcaa5f8c2b0a54f6491913a01c2e20ac6adad79476"
      url "https://github.com/shibukawa/localotelviewer/releases/download/v#{version}/localotelviewer_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "513c9aa020321a6253df54ee8712f40d7a5f3aff6db539563604a5cced75bdea"
      url "https://github.com/shibukawa/localotelviewer/releases/download/v#{version}/localotelviewer_#{version}_linux_arm64.tar.gz"
    end
  end

  name "localotelviewer"
  desc "Ephemeral local OpenTelemetry viewer with OTLP receiver and embedded web UI"
  homepage "https://github.com/shibukawa/localotelviewer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "localotelviewer"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/localotelviewer"]
    end
  end

  # No zap stanza required

end
