# This file was generated by GoReleaser. DO NOT EDIT.
cask "localotelviewer" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "25ded85e5d184f237089d7e741e0b6c93ffb65dc4e918e5ccd2b8a458cbb8891"
      url "https://github.com/shibukawa/localotelviewer/releases/download/v#{version}/localotelviewer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7c8ba5c2bc12b329904130c9c23fd06a0f80c6003903d60c90a19b486442e1dd"
      url "https://github.com/shibukawa/localotelviewer/releases/download/v#{version}/localotelviewer_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3aee7e296c623bf0968e2e17590440dfda8353853570ff1c4f41797e5c61d02e"
      url "https://github.com/shibukawa/localotelviewer/releases/download/v#{version}/localotelviewer_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "752675338c6cab7c7591962b46537203afb683eb2db8492a94daa6ee5005eed4"
      url "https://github.com/shibukawa/localotelviewer/releases/download/v#{version}/localotelviewer_#{version}_linux_arm64.tar.gz"
    end
  end

  name "localotelviewer"
  desc "Ephemeral local OpenTelemetry viewer with OTLP receiver and embedded web UI"
  homepage "https://github.com/shibukawa/localotelviewer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "localotelviewer"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/localotelviewer"]
    end
  end

  # No zap stanza required

end
