# This file was generated by GoReleaser. DO NOT EDIT.
cask "localotelviewer" do
  version "1.0.4"

  on_macos do
    on_intel do
      sha256 "4c7ae69777de88160a4d6a4ee4bd86d097ece03baf305dd9a8f4b3f3d18624a4"
      url "https://github.com/shibukawa/localotelviewer/releases/download/v#{version}/localotelviewer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fbf11c3c3200b180ca86533ba110f1117db24efa0fe5e33e8040488cdc62cec3"
      url "https://github.com/shibukawa/localotelviewer/releases/download/v#{version}/localotelviewer_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "22dca6c31e844d1b1453b58fcfa5c09dadefe54b97fecb211ccf4d03c634991d"
      url "https://github.com/shibukawa/localotelviewer/releases/download/v#{version}/localotelviewer_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3cb4db2466108cb3b04ed4730e3231f2150769e3926b6d1d4c8cbdb179a249ed"
      url "https://github.com/shibukawa/localotelviewer/releases/download/v#{version}/localotelviewer_#{version}_linux_arm64.tar.gz"
    end
  end

  name "localotelviewer"
  desc "Ephemeral local OpenTelemetry viewer with OTLP receiver and embedded web UI"
  homepage "https://github.com/shibukawa/localotelviewer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "localotelviewer"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/localotelviewer"]
    end
  end

  # No zap stanza required

end
